import os

PROJECT_ROOT = os.getcwd()
DEFAULT_PRESET_JSON_PATH = os.path.join(
    PROJECT_ROOT, "presetml", "parsing", "default_dict.json"
)

TEST_PRESETS_PATH = os.path.join(PROJECT_ROOT, "data", "test_presets")
ANALOG_PRESETS_PATH = os.path.join(PROJECT_ROOT, "data", "analog_library")
GENERATED_PRESETS_DIR = os.path.join(PROJECT_ROOT, "data", "generated")

CGAN_LABELS = ["Lead", "Pad", "Bass", "Brass", "Strings", "Keys"]


CATEGORICAL_RANGES = {
    "OscillatorWaveShape": 4,
    "FilterType": 10,
    "FilterDrive": 7,  # 0 is off
    "LFOWaveShape": 5,
    "PortamentoMode": 2,
    "Loop": 4,  # 0 is off
}

TARGET_KEYS = [
    # ["Ableton", "UltraAnalog", "Polyphony"],
    ["Ableton", "UltraAnalog", "PitchBendRange"],
    ["Ableton", "UltraAnalog", "Volume"],
    ["Ableton", "UltraAnalog", "Octave"],
    # ["Ableton", "UltraAnalog", "OctaveRelativePosition"],
    ["Ableton", "UltraAnalog", "Transpose"],
    # ["Ableton", "UltraAnalog", "TransposeRelativePosition"],
    # ["Ableton", "UltraAnalog", "KeyboardFineTune"],
    ["Ableton", "UltraAnalog", "KeyboardUnisonToggle"],
    ["Ableton", "UltraAnalog", "KeyboardUnison"],
    # ["Ableton", "UltraAnalog", "KeyboardDetune"],
    ["Ableton", "UltraAnalog", "KeyboardUnisonDelay"],
    # ["Ableton", "UltraAnalog", "KeyboardPriority"],
    # ["Ableton", "UltraAnalog", "KeyboardStretch"],
    # ["Ableton", "UltraAnalog", "KeyboardError"],
    ["Ableton", "UltraAnalog", "VibratoToggle"],
    ["Ableton", "UltraAnalog", "VibratoSpeed"],
    ["Ableton", "UltraAnalog", "VibratoFadeIn"],
    ["Ableton", "UltraAnalog", "VibratoAmount"],
    ["Ableton", "UltraAnalog", "VibratoError"],
    ["Ableton", "UltraAnalog", "VibratoDelay"],
    ["Ableton", "UltraAnalog", "VibratoModWheel"],
    ["Ableton", "UltraAnalog", "PortamentoToggle"],
    ["Ableton", "UltraAnalog", "PortamentoTime"],
    ["Ableton", "UltraAnalog", "PortamentoMode"],
    ["Ableton", "UltraAnalog", "PortamentoLegato"],
    ["Ableton", "UltraAnalog", "NoiseToggle"],
    ["Ableton", "UltraAnalog", "NoiseColor"],
    ["Ableton", "UltraAnalog", "NoiseBalance"],
    ["Ableton", "UltraAnalog", "NoiseLevel"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorToggle"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorWaveShape"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorOct"],
    # ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorOctRelativePosition"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorSemi"],
    # ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorSemiRelativePosition"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorMode"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorEnvTime"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorDetune"],
    # ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorModulation1"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorPulseWidth"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorSubAmount"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorBalance"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorEnvAmount"],
    # ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorLFOModPitch"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorLFOModPW"],
    ["Ableton", "UltraAnalog", "SignalChain1", "OscillatorLevel"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterToggle"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterType"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterDrive"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterKbdCutoffMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterCutoffFrequency"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterKbdQMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterQFactor"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterLFOCutoffMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterEnvCutoffMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterLFOQMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterEnvQMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "AmplifierToggle"],
    ["Ableton", "UltraAnalog", "SignalChain1", "AmplifierKbdAmpMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "AmplifierLevel"],
    ["Ableton", "UltraAnalog", "SignalChain1", "AmplifierKbdPanMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "AmplifierPan"],
    ["Ableton", "UltraAnalog", "SignalChain1", "AmplifierLFOAmpMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "AmplifierLFOPanMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "AmplifierEnvPanMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "LFOToggle"],
    ["Ableton", "UltraAnalog", "SignalChain1", "LFOWaveShape"],
    ["Ableton", "UltraAnalog", "SignalChain1", "LFOSync"],
    ["Ableton", "UltraAnalog", "SignalChain1", "LFOSyncToggle"],
    ["Ableton", "UltraAnalog", "SignalChain1", "LFOGateReset"],
    ["Ableton", "UltraAnalog", "SignalChain1", "LFOPulseWidth"],
    ["Ableton", "UltraAnalog", "SignalChain1", "LFOSpeed"],
    ["Ableton", "UltraAnalog", "SignalChain1", "LFOPhase"],
    ["Ableton", "UltraAnalog", "SignalChain1", "LFODelay"],
    ["Ableton", "UltraAnalog", "SignalChain1", "LFOFadeIn"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "ExponentialSlope"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "Loop"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "FreeRun"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "Legato"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "AttackMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "AttackTime"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "DecayTime"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "AmpMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "SustainLevel"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "SustainTime"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.0", "ReleaseTime"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "ExponentialSlope"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "Loop"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "FreeRun"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "Legato"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "AttackMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "AttackTime"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "DecayTime"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "AmpMod"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "SustainLevel"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "SustainTime"],
    ["Ableton", "UltraAnalog", "SignalChain1", "Envelope.1", "ReleaseTime"],
    ["Ableton", "UltraAnalog", "SignalChain1", "FilterToFilter2"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorToggle"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorWaveShape"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorOct"],
    # ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorOctRelativePosition"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorSemi"],
    # ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorSemiRelativePosition"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorMode"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorEnvTime"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorDetune"],
    # ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorModulation1"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorPulseWidth"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorSubAmount"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorBalance"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorEnvAmount"],
    # ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorLFOModPitch"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorLFOModPW"],
    ["Ableton", "UltraAnalog", "SignalChain2", "OscillatorLevel"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterToggle"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterType"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterDrive"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterKbdCutoffMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterCutoffFrequency"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterKbdQMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterQFactor"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterLFOCutoffMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterEnvCutoffMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterLFOQMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterEnvQMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "AmplifierToggle"],
    ["Ableton", "UltraAnalog", "SignalChain2", "AmplifierKbdAmpMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "AmplifierLevel"],
    ["Ableton", "UltraAnalog", "SignalChain2", "AmplifierKbdPanMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "AmplifierPan"],
    ["Ableton", "UltraAnalog", "SignalChain2", "AmplifierLFOAmpMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "AmplifierLFOPanMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "AmplifierEnvPanMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "LFOToggle"],
    ["Ableton", "UltraAnalog", "SignalChain2", "LFOWaveShape"],
    ["Ableton", "UltraAnalog", "SignalChain2", "LFOSync"],
    ["Ableton", "UltraAnalog", "SignalChain2", "LFOSyncToggle"],
    ["Ableton", "UltraAnalog", "SignalChain2", "LFOGateReset"],
    ["Ableton", "UltraAnalog", "SignalChain2", "LFOPulseWidth"],
    ["Ableton", "UltraAnalog", "SignalChain2", "LFOSpeed"],
    ["Ableton", "UltraAnalog", "SignalChain2", "LFOPhase"],
    ["Ableton", "UltraAnalog", "SignalChain2", "LFODelay"],
    ["Ableton", "UltraAnalog", "SignalChain2", "LFOFadeIn"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.0", "Loop"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.0", "FreeRun"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.0", "Legato"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.0", "AttackMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.0", "AttackTime"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.0", "DecayTime"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.0", "AmpMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.0", "SustainLevel"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.0", "SustainTime"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.0", "ReleaseTime"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "ExponentialSlope"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "Loop"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "FreeRun"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "Legato"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "AttackMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "AttackTime"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "DecayTime"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "AmpMod"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "SustainLevel"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "SustainTime"],
    ["Ableton", "UltraAnalog", "SignalChain2", "Envelope.1", "ReleaseTime"],
    ["Ableton", "UltraAnalog", "SignalChain2", "FilterSlave"],
]
